apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob2sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bob2sa-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob2-rolebinding
roleRef:
  apiGroup: ""
  kind: Role
  name: bob2sa-role
subjects:
- kind: ServiceAccount
  name: bob2sa
  apiGroup: ""
